/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.iglesia.escuela.vistas.alumnos;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JPanel;

/**
 *
 * @author arzuz
 */
public class EditorAlumnosConExcelVista extends javax.swing.JDialog {

    /**
     * Creates new form EditorAlumnoVista
     */
    public EditorAlumnosConExcelVista(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tipoButtonGroup.add(agregarCheck);
        tipoButtonGroup.add(actualizarCheck);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        agregarCheck = new javax.swing.JCheckBox();
        actualizarCheck = new javax.swing.JCheckBox();
        importarButton = new javax.swing.JButton();
        importandoPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        importandoProgress = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        formatoAgregarButton = new javax.swing.JButton();
        formatoActualizarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editor de Alumnos con Excel");
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 62));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 20));

        agregarCheck.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        agregarCheck.setSelected(true);
        agregarCheck.setText("Agregar");
        agregarCheck.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        agregarCheck.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(agregarCheck);

        actualizarCheck.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        actualizarCheck.setText("Actualizar");
        actualizarCheck.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(actualizarCheck);

        importarButton.setText("Importar");
        importarButton.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel1.add(importarButton);

        importandoPanel.setPreferredSize(new java.awt.Dimension(200, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Importando...");
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 20));
        importandoPanel.add(jLabel3);

        importandoProgress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        importandoProgress.setIndeterminate(true);
        importandoProgress.setPreferredSize(new java.awt.Dimension(200, 10));
        importandoPanel.add(importandoProgress);

        jPanel1.add(importandoPanel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        formatoAgregarButton.setText("Formato Agregar");
        formatoAgregarButton.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel2.add(formatoAgregarButton);

        formatoActualizarButton.setText("Formato Actualizar");
        formatoActualizarButton.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel2.add(formatoActualizarButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JCheckBox getActualizarCheck() {
        return actualizarCheck;
    }

    public JCheckBox getAgregarCheck() {
        return agregarCheck;
    }

    public JButton getFormatoActualizarButton() {
        return formatoActualizarButton;
    }

    public JButton getFormatoAgregarButton() {
        return formatoAgregarButton;
    }

    public JPanel getImportandoPanel() {
        return importandoPanel;
    }

    public JButton getImportarButton() {
        return importarButton;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorAlumnosConExcelVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorAlumnosConExcelVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorAlumnosConExcelVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorAlumnosConExcelVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditorAlumnosConExcelVista dialog = new EditorAlumnosConExcelVista(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox actualizarCheck;
    private javax.swing.JCheckBox agregarCheck;
    private javax.swing.JButton formatoActualizarButton;
    private javax.swing.JButton formatoAgregarButton;
    private javax.swing.JPanel importandoPanel;
    private javax.swing.JProgressBar importandoProgress;
    private javax.swing.JButton importarButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.ButtonGroup tipoButtonGroup;
    // End of variables declaration//GEN-END:variables
}
