/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.iglesia.escuela.vistas.alumnos;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author arzuz
 */
public class EditorAlumnoVista extends javax.swing.JDialog {

    /**
     * Creates new form EditorAlumnoVista
     */
    public EditorAlumnoVista(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellidoField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        telefonoField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        materiaCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        GradoCombo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        GuardarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editor de Alumno");
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 400));

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 62));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombres:");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel1.add(jLabel2);

        nombreField.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel1.add(nombreField);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Apellidos:");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel1.add(jLabel3);

        apellidoField.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel1.add(apellidoField);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Telefono:");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel1.add(jLabel4);

        telefonoField.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel1.add(telefonoField);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Materia:");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel1.add(jLabel5);

        materiaCombo.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel1.add(materiaCombo);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Grado:");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel1.add(jLabel6);

        GradoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Pasos", "2. Fundamentos I", "3. Fundamentos II", "4. Liderazgo I", "5. Liderazgo II", "6. Liderazgo III", "7. Liderazgo IV", "8. Practicantes" }));
        GradoCombo.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel1.add(GradoCombo);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        GuardarButton.setText("Guardar");
        GuardarButton.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel2.add(GuardarButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JComboBox<String> getGradoCombo() {
        return GradoCombo;
    }

    public JButton getGuardarButton() {
        return GuardarButton;
    }

    public JTextField getApellidoField() {
        return apellidoField;
    }

    public JTextField getTelefonoField() {
        return telefonoField;
    }

    public JComboBox<String> getMateriaCombo() {
        return materiaCombo;
    }

    public JTextField getNombreField() {
        return nombreField;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorAlumnoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorAlumnoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorAlumnoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorAlumnoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditorAlumnoVista dialog = new EditorAlumnoVista(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> GradoCombo;
    private javax.swing.JButton GuardarButton;
    private javax.swing.JTextField apellidoField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> materiaCombo;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField telefonoField;
    // End of variables declaration//GEN-END:variables
}
