/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.iglesia.escuela.vistas.calificaciones;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author arzuz
 */
public class EditorCalificacionesVista extends javax.swing.JDialog {

    /**
     * Creates new form EditorAlumnoVista
     */
    public EditorCalificacionesVista(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        imprimirButton = new javax.swing.JButton();
        agregarButton = new javax.swing.JButton();
        actualizarButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        apellidoLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        gradoLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        calificacionesTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        estatusLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        calificacionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editor de Calificaciones");
        setMinimumSize(new java.awt.Dimension(690, 600));
        setPreferredSize(new java.awt.Dimension(690, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(690, 600));

        jPanel8.setPreferredSize(new java.awt.Dimension(100, 105));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        imprimirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imprimir.png"))); // NOI18N
        imprimirButton.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel3.add(imprimirButton);

        agregarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        agregarButton.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel3.add(agregarButton);

        actualizarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        actualizarButton.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel3.add(actualizarButton);

        jPanel8.add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Nombre:");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel5.add(jLabel6);

        nombreLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreLabel.setPreferredSize(new java.awt.Dimension(450, 20));
        jPanel5.add(nombreLabel);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Apellido:");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel5.add(jLabel5);

        apellidoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        apellidoLabel.setPreferredSize(new java.awt.Dimension(450, 20));
        jPanel5.add(apellidoLabel);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Grado:");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel5.add(jLabel7);

        gradoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gradoLabel.setPreferredSize(new java.awt.Dimension(450, 20));
        jPanel5.add(gradoLabel);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Telefono:");
        jLabel10.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel5.add(jLabel10);

        telefonoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telefonoLabel.setPreferredSize(new java.awt.Dimension(450, 20));
        jPanel5.add(telefonoLabel);

        jPanel8.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 62));
        jPanel1.setLayout(new java.awt.BorderLayout());

        calificacionesTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        calificacionesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        calificacionesTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(calificacionesTable);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Estado:");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel2.add(jLabel3);

        estatusLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        estatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estatusLabel.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel2.add(estatusLabel);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Calificación:");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel2.add(jLabel4);

        calificacionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        calificacionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calificacionLabel.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel2.add(calificacionLabel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JButton getActualizarButton() {
        return actualizarButton;
    }

    public JButton getAgregarButton() {
        return agregarButton;
    }

    public JLabel getApellidoLabel() {
        return apellidoLabel;
    }

    public JTable getCalificacionesTable() {
        return calificacionesTable;
    }

    public JLabel getCalificacionLabel() {
        return calificacionLabel;
    }

    public JLabel getEstatusLabel() {
        return estatusLabel;
    }

    public JLabel getGradoLabel() {
        return gradoLabel;
    }

    public JButton getImprimirButton() {
        return imprimirButton;
    }

    public JLabel getNombreLabel() {
        return nombreLabel;
    }

    public JLabel getTelefonoLabel() {
        return telefonoLabel;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorCalificacionesVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorCalificacionesVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorCalificacionesVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorCalificacionesVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditorCalificacionesVista dialog = new EditorCalificacionesVista(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarButton;
    private javax.swing.JButton agregarButton;
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JLabel calificacionLabel;
    private javax.swing.JTable calificacionesTable;
    private javax.swing.JLabel estatusLabel;
    private javax.swing.JLabel gradoLabel;
    private javax.swing.JButton imprimirButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel telefonoLabel;
    // End of variables declaration//GEN-END:variables
}
