package com.iglesia.escuela.vistas.curso;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

public class CursosVista extends javax.swing.JPanel {

    /**
     * Creates new form alumnosVista
     */
    public CursosVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buscarField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        agregarButton = new javax.swing.JButton();
        actualizarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cursosTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cantidadLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Buscar:");
        jLabel2.setPreferredSize(new java.awt.Dimension(60, 40));
        jPanel1.add(jLabel2, java.awt.BorderLayout.LINE_START);

        buscarField.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel1.add(buscarField, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));

        agregarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        agregarButton.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel3.add(agregarButton);

        actualizarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        actualizarButton.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel3.add(actualizarButton);

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_END);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        cursosTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cursosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        cursosTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(cursosTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(790, 40));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("#");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel2.add(jLabel3);

        cantidadLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cantidadLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadLabel.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel2.add(cantidadLabel);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    public JTable getCursosTable() {
        return cursosTable;
    }

    public JTextField getBuscarField() {
        return buscarField;
    }

    public JLabel getCantidadLabel() {
        return cantidadLabel;
    }

    public JButton getActualizarButton() {
        return actualizarButton;
    }

    public JButton getAgregarButton() {
        return agregarButton;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarButton;
    private javax.swing.JButton agregarButton;
    private javax.swing.JTextField buscarField;
    private javax.swing.JLabel cantidadLabel;
    private javax.swing.JTable cursosTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
