/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iglesia.escuela.vistas.principal;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author arzuz
 */
public class PrincipalVista extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalVista
     */
    public PrincipalVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        usuariosButton = new javax.swing.JButton();
        alumnosButton = new javax.swing.JButton();
        cursosButton = new javax.swing.JButton();
        calificacionesButton = new javax.swing.JButton();
        asistenciasButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        salirButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        contenidoPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escuela de Formación");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 600));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setForeground(new java.awt.Color(0, 153, 255));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        usuariosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nota.png"))); // NOI18N
        usuariosButton.setText("Usuarios");
        usuariosButton.setPreferredSize(new java.awt.Dimension(180, 40));
        jPanel3.add(usuariosButton);

        alumnosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alumnos.png"))); // NOI18N
        alumnosButton.setText("Alumnos");
        alumnosButton.setPreferredSize(new java.awt.Dimension(180, 40));
        jPanel3.add(alumnosButton);

        cursosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cursos.png"))); // NOI18N
        cursosButton.setText("Cursos");
        cursosButton.setPreferredSize(new java.awt.Dimension(180, 40));
        jPanel3.add(cursosButton);

        calificacionesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calificaciones.png"))); // NOI18N
        calificacionesButton.setText("Calificaciones");
        calificacionesButton.setPreferredSize(new java.awt.Dimension(180, 40));
        jPanel3.add(calificacionesButton);

        asistenciasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/asistencia.png"))); // NOI18N
        asistenciasButton.setText("Asistencias");
        asistenciasButton.setPreferredSize(new java.awt.Dimension(180, 40));
        jPanel3.add(asistenciasButton);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        salirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        salirButton.setText("Salir");
        salirButton.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel4.add(salirButton);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        contenidoPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(contenidoPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JButton getAlumnosButton() {
        return alumnosButton;
    }

    public JButton getAsistenciasButton() {
        return asistenciasButton;
    }

    public JButton getCalificacionesButton() {
        return calificacionesButton;
    }

    public JPanel getContenidoPanel() {
        return contenidoPanel;
    }

    public JButton getCursosButton() {
        return cursosButton;
    }

    public JButton getSalirButton() {
        return salirButton;
    }

    public JButton getUsuariosButton() {
        return usuariosButton;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alumnosButton;
    private javax.swing.JButton asistenciasButton;
    private javax.swing.JButton calificacionesButton;
    private javax.swing.JPanel contenidoPanel;
    private javax.swing.JButton cursosButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton salirButton;
    private javax.swing.JButton usuariosButton;
    // End of variables declaration//GEN-END:variables
}
