package com.iglesia.escuela.vistas.asistencias;

import com.toedter.calendar.JDateChooser;
import java.util.Date;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

public class AsistenciasVista extends javax.swing.JPanel {

    /**
     * Creates new form alumnosVista
     */
    public AsistenciasVista() {
        initComponents();
        fechaChooser.setLocale(Locale.of("es", "ES"));
        fechaChooser.setMaxSelectableDate(new Date());
        ((JTextField) fechaChooser.getDateEditor().getUiComponent()).setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fechaChooser = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        marcarAsistenciasButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        asistenciasTable = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 5, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 75));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Fecha:");
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel7.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        fechaChooser.setDateFormatString("yyyy/MM/dd");
        fechaChooser.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel7.add(fechaChooser, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel7);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        marcarAsistenciasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        marcarAsistenciasButton.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel3.add(marcarAsistenciasButton);

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_END);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        asistenciasTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        asistenciasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        asistenciasTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(asistenciasTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public JTable getAsistenciasTable() {
        return asistenciasTable;
    }

    public JButton getMarcarAsistenciasButton() {
        return marcarAsistenciasButton;
    }

    public JDateChooser getFechaChooser() {
        return fechaChooser;
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable asistenciasTable;
    private com.toedter.calendar.JDateChooser fechaChooser;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton marcarAsistenciasButton;
    // End of variables declaration//GEN-END:variables
}
