/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.iglesia.escuela.vistas.asistencias;

import com.toedter.calendar.JDateChooser;
import java.util.Date;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author arzuz
 */
public class EditorAsistenciaVista extends javax.swing.JDialog {

    /**
     * Creates new form EditorAlumnoVista
     */
    public EditorAsistenciaVista(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fechaChooser.setLocale(Locale.of("es", "ES"));
        fechaChooser.setMaxSelectableDate(new Date());
        ((JTextField) fechaChooser.getDateEditor().getUiComponent()).setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fechaChooser = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        materiaCombo = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        gradoCombo = new javax.swing.JComboBox<>();
        buscarButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        asistenciasTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        guardarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editor de Asistencias");
        setMinimumSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 400));

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Fecha:");
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel6.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        fechaChooser.setDateFormatString("yyyy/MM/dd");
        fechaChooser.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel6.add(fechaChooser, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Materia:");
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel4.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        materiaCombo.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel4.add(materiaCombo, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel4);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Grado:");
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel7.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        gradoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Pasos", "2. Fundamentos I", "3. Fundamentos II", "4. Liderazgo I", "5. Liderazgo II", "6. Liderazgo III", "7. Liderazgo IV", "8. Practicantes" }));
        gradoCombo.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel7.add(gradoCombo, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel7);

        buscarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alumnos.png"))); // NOI18N
        buscarButton.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel5.add(buscarButton);

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 62));
        jPanel1.setLayout(new java.awt.BorderLayout());

        asistenciasTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        asistenciasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        asistenciasTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(asistenciasTable);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        guardarButton.setText("Guardar");
        guardarButton.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel2.add(guardarButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JTable getAsistenciasTable() {
        return asistenciasTable;
    }

    public JComboBox<String> getGradoCombo() {
        return gradoCombo;
    }

    public JButton getGuardarButton() {
        return guardarButton;
    }

    public JComboBox<String> getMateriaCombo() {
        return materiaCombo;
    }

    public JButton getBuscarButton() {
        return buscarButton;
    }

    public JDateChooser getFechaChooser() {
        return fechaChooser;
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorAsistenciaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorAsistenciaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorAsistenciaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorAsistenciaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditorAsistenciaVista dialog = new EditorAsistenciaVista(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable asistenciasTable;
    private javax.swing.JButton buscarButton;
    private com.toedter.calendar.JDateChooser fechaChooser;
    private javax.swing.JComboBox<String> gradoCombo;
    private javax.swing.JButton guardarButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> materiaCombo;
    // End of variables declaration//GEN-END:variables
}
