parent=FlatLightLaf

Component.arc=20
ProgressBar.arc=20
TextComponent.arc=20
Button.arc=20
CheckBox.arc=20
RadioButton.arc=20
Spinner.arc=20
ScrollBar.thumbArc=20
PopupMenu.borderArc=10
Component.focusWidth=1